// Generated by Wrangler by running `wrangler types`, plus the board bindings.

interface Env {
	TO_DO_LIST: KVNamespace;
	/** The Gamino board. Points at the same namespace as TO_DO_LIST, under a `board:` key prefix. */
	BOARD: KVNamespace;
	/** Master write token. Per-seat keys are derived from it. Set with `wrangler secret put BOARD_TOKEN`. */
	BOARD_TOKEN?: string;
}
