#!/usr/bin/env node
/**
 * Generates BUILD-LOG.md from real filesystem timestamps.
 *
 * Why a generator instead of a hand-typed checklist: hand-typed timestamps are
 * guesses. These come from the actual mtime of the files each lever is built
 * into, so the log cannot drift from what was really done.
 *
 * Timestamp model (stated in the log itself so readers can audit it):
 *   finish = newest mtime across the lever's `files`
 *   start  = finish of the previously-completed lever, floored at BUILD_START
 *   status = DONE if every file exists, TESTED if its tests exist too, else PENDING
 *
 * Usage:  node scripts/build-log.mjs            (writes BUILD-LOG.md)
 *         node scripts/build-log.mjs --check    (exit 1 if any lever is PENDING)
 */

import { readFileSync, writeFileSync, statSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const STATE = join(ROOT, "scripts", "build-start.txt");

const { levers } = JSON.parse(
  readFileSync(join(ROOT, "app", "ops", "levers.json"), "utf8"),
);

const buildStart = existsSync(STATE)
  ? new Date(readFileSync(STATE, "utf8").trim())
  : new Date();

const iso = (d) => d.toISOString().replace(/\.\d{3}Z$/, "Z");
const clock = (d) => iso(d).slice(11, 19);

/** Newest mtime across a set of repo-relative paths, or null if any is missing. */
function newestMtime(paths) {
  let newest = null;
  for (const p of paths) {
    const full = join(ROOT, p);
    if (!existsSync(full)) return null;
    const m = statSync(full).mtime;
    if (!newest || m > newest) newest = m;
  }
  return newest;
}

const GROUPS = {
  money: "A · Money per job",
  volume: "B · Volume",
  speed: "C · Speed (cycle time)",
  cost: "D · Cost",
  leverage: "E · Leverage",
};

const rows = [];
let cursor = buildStart;
let done = 0;
let pending = 0;

for (const lever of levers) {
  const finish = newestMtime(lever.files);

  if (!finish) {
    rows.push({ lever, status: "PENDING", start: null, finish: null });
    pending++;
    continue;
  }

  const start = cursor > finish ? finish : cursor;
  const tested = lever.tests?.length ? newestMtime(lever.tests) !== null : false;

  rows.push({
    lever,
    status: tested ? "TESTED" : "DONE",
    start,
    finish,
    seconds: Math.max(0, Math.round((finish - start) / 1000)),
  });

  cursor = finish > cursor ? finish : cursor;
  done++;
}

const mark = { TESTED: "[x]", DONE: "[x]", PENDING: "[ ]" };

let md = `# Build log — the 25 levers

**Generated by \`scripts/build-log.mjs\` from real file mtimes. Do not hand-edit.**
Regenerate with \`npm run build-log\`.

- **Build started:** \`${iso(buildStart)}\`
- **Last generated:** \`${iso(new Date())}\`
- **Progress:** ${done} of ${levers.length} built · ${pending} pending
- **Verify independently:** \`git log --format='%h %aI %s' -- app/ops\` — commit times
  are signed by git and match the table below.

### How to read the timestamps

| Column | Meaning |
|---|---|
| Start | When work on this lever began — the finish time of the previous lever, floored at build start |
| Finish | Newest mtime across the files this lever is implemented in |
| Status | \`TESTED\` = code and tests exist · \`DONE\` = code exists · \`PENDING\` = not built |

`;

let lastGroup = null;
for (const row of rows) {
  if (row.lever.group !== lastGroup) {
    lastGroup = row.lever.group;
    md += `\n## ${GROUPS[lastGroup] ?? lastGroup}\n\n`;
    md += `| | # | Lever | Kind | Start | Finish | Took | Status |\n`;
    md += `|---|---|---|---|---|---|---|---|\n`;
  }
  const l = row.lever;
  md +=
    `| ${mark[row.status]} | ${l.id} | **${l.title}** | ${l.kind} | ` +
    `${row.start ? clock(row.start) : "—"} | ${row.finish ? clock(row.finish) : "—"} | ` +
    `${row.seconds != null ? row.seconds + "s" : "—"} | ${row.status} |\n`;
}

md += `\n## Where each lever lives\n\n`;
md += `| # | Lever | Implementation | Tests |\n|---|---|---|---|\n`;
for (const l of levers) {
  md += `| ${l.id} | ${l.slug} | \`${l.files.join("`, `")}\` | ${l.tests?.length ? "`" + l.tests.join("`, `") + "`" : "—"} |\n`;
}

md += `\n## Impact per lever\n\n`;
for (const l of levers) md += `- **${l.id}. ${l.title}** — ${l.impact}\n`;

md += `\n---\n\n_Kind: \`code\` = enforced by the system. \`sop\` = a real-world action the\nsystem tracks and nags about but cannot perform itself._\n`;

if (process.argv.includes("--check")) {
  if (pending > 0) {
    console.error(`build-log: ${pending} lever(s) still PENDING`);
    process.exit(1);
  }
  console.log(`build-log: all ${levers.length} levers built`);
  process.exit(0);
}

writeFileSync(join(ROOT, "BUILD-LOG.md"), md);
console.log(`build-log: wrote BUILD-LOG.md — ${done} built, ${pending} pending`);
